### ISSUE TITLE
Repo 이름 수정 요청합니다.

### ISSUE THREAD

**Issue by Joylish** [kwak-bs/T-T#3]
# 2021년 맞이 Repo 새이름 요청

## ☹ 현재 이름 문제점
레포 소유자랑 쩜.. 안 어울리는거 같습니다. TT는 트와이스처럼 상큼한 사람한테 어울립니다. 바로 저처럼요 ^^

## 😎 이름 추천
TT 말고 **튀튀** 추천합니다!

**Comment by kwak-bs** [comment]
T-T는 TIL + Toyproject의 줄임말입니다. 말씀하신 의도는 잘 알겠으나 추천하신 이름은 아마 절대로 반영은 되지 않을것 같습니다. 다음에 저와 마주친다면 바로 튀튀 하시는게 좋을 것 같습니다.
