### ISSUE TITLE
클래스는 다중상속이 안되는 것을 알게되었습니다

### ISSUE THREAD

**Issue by Joylish** [kwak-bs/T-T#4]
# 감사합니다😁😁😁😁😁😁😁

클래스는 단일상속만 되기 때문에 인터페이스로 극복하는 거였군요!

정리의 신🐲이시네요

[바로 이 TIL](https://github.com/kwak-bs/T-T/blob/master/Java/TIL_02_OOP_Inheritance.md)

**Comment by kwak-bs** [comment]
하하 정말 힘이나는 이슈를 올려주셨습니다. 자바에서의 상속은 정말 중요한 개념이니 꼭 숙지하시길 바랍니다. 어느 면접에서 나올지 모르거든요. ^^ 그리고 진짜 다음에 저와 마주치신다면 꼭 튀튀하시길 바라겠습니다. 죄목은 의도 불순죄입니다.
